In [40]:
import pandas as pd #for data manipulation
import numpy as np   #for numerical ops
import matplotlib.pyplot as plt  #for visualization like graphs
import matplotlib.style  # for styling such as font etc
import seaborn as sns #for visualization and data analysis like heatmaps
import warnings
warnings.filterwarnings('ignore') #supresses warnings

**accuracy_score**: To calculate the proportion of correct predictions.
**precision_score**: To measure the proportion of true positive predictions among all positive predictions.
**recall_score**: To measure the proportion of true positive predictions among all actual positive instances.
**f1_score**: The harmonic mean of precision and recall, useful for balancing both.

In [41]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

In [42]:
#Data loading
import kagglehub

path=kagglehub.dataset_download("shantanudhakadd/email-spam-detection-dataset-classification")
print("Path :: ", path)

Using Colab cache for faster access to the 'email-spam-detection-dataset-classification' dataset.
Path ::  /kaggle/input/email-spam-detection-dataset-classification

In [43]:
import kagglehub
import pandas as pd

# Force a fresh download (not using Colab cache)
path = kagglehub.dataset_download(
    "shantanudhakadd/email-spam-detection-dataset-classification",
    force_download=True   # ensures a new copy is downloaded
)

print("Downloaded Path ::", path)

# Check the files inside the dataset folder
!ls {path}

# Load the CSV into a DataFrame (replace with actual filename)
df = pd.read_csv(dataset_path, encoding="latin1")
df.head()

Using Colab cache for faster access to the 'email-spam-detection-dataset-classification' dataset.
Downloaded Path :: /kaggle/input/email-spam-detection-dataset-classification
spam.csv

,v1,v2,Unnamed: 2,Unnamed: 3,Unnamed: 4
0,ham,"Go until jurong point, crazy.. Available only ...",NaN,NaN,NaN
1,ham,Ok lar... Joking wif u oni...,NaN,NaN,NaN
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,NaN,NaN,NaN
3,ham,U dun say so early hor... U c already then say...,NaN,NaN,NaN
4,ham,"Nah I don't think he goes to usf, he lives aro...",NaN,NaN,NaN

In [44]:
dataset_path=" /kaggle/input/email-spam-detection-dataset-classification/spam.csv" #loads the csv into the df dataframe

In [46]:
df = pd.read_csv(dataset_path.strip(), encoding= "latin1") #latin since the dataset was in it

PERFORMING EDA

In [47]:
df.tail #shows few rows

<bound method NDFrame.tail of         v1                                                 v2 Unnamed: 2  \
0      ham  Go until jurong point, crazy.. Available only ...        NaN
1      ham                      Ok lar... Joking wif u oni...        NaN
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...        NaN
3      ham  U dun say so early hor... U c already then say...        NaN
4      ham  Nah I don't think he goes to usf, he lives aro...        NaN
...    ...                                                ...        ...
5567  spam  This is the 2nd time we have tried 2 contact u...        NaN
5568   ham              Will Ì_ b going to esplanade fr home?        NaN
5569   ham  Pity, * was in mood for that. So...any other s...        NaN
5570   ham  The guy did some bitching but I acted like i'd...        NaN
5571   ham                         Rofl. Its true to its name        NaN

     Unnamed: 3 Unnamed: 4
0           NaN        NaN
1           NaN        NaN
2           NaN        NaN
3           NaN        NaN
4           NaN        NaN
...         ...        ...
5567        NaN        NaN
5568        NaN        NaN
5569        NaN        NaN
5570        NaN        NaN
5571        NaN        NaN

[5572 rows x 5 columns]>

In [48]:
df.info #summary

<bound method DataFrame.info of         v1                                                 v2 Unnamed: 2  \
0      ham  Go until jurong point, crazy.. Available only ...        NaN
1      ham                      Ok lar... Joking wif u oni...        NaN
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...        NaN
3      ham  U dun say so early hor... U c already then say...        NaN
4      ham  Nah I don't think he goes to usf, he lives aro...        NaN
...    ...                                                ...        ...
5567  spam  This is the 2nd time we have tried 2 contact u...        NaN
5568   ham              Will Ì_ b going to esplanade fr home?        NaN
5569   ham  Pity, * was in mood for that. So...any other s...        NaN
5570   ham  The guy did some bitching but I acted like i'd...        NaN
5571   ham                         Rofl. Its true to its name        NaN

     Unnamed: 3 Unnamed: 4
0           NaN        NaN
1           NaN        NaN
2           NaN        NaN
3           NaN        NaN
4           NaN        NaN
...         ...        ...
5567        NaN        NaN
5568        NaN        NaN
5569        NaN        NaN
5570        NaN        NaN
5571        NaN        NaN

[5572 rows x 5 columns]>

In [50]:
df.describe #descriptive statistics

<bound method NDFrame.describe of         v1                                                 v2 Unnamed: 2  \
0      ham  Go until jurong point, crazy.. Available only ...        NaN
1      ham                      Ok lar... Joking wif u oni...        NaN
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...        NaN
3      ham  U dun say so early hor... U c already then say...        NaN
4      ham  Nah I don't think he goes to usf, he lives aro...        NaN
...    ...                                                ...        ...
5567  spam  This is the 2nd time we have tried 2 contact u...        NaN
5568   ham              Will Ì_ b going to esplanade fr home?        NaN
5569   ham  Pity, * was in mood for that. So...any other s...        NaN
5570   ham  The guy did some bitching but I acted like i'd...        NaN
5571   ham                         Rofl. Its true to its name        NaN

     Unnamed: 3 Unnamed: 4
0           NaN        NaN
1           NaN        NaN
2           NaN        NaN
3           NaN        NaN
4           NaN        NaN
...         ...        ...
5567        NaN        NaN
5568        NaN        NaN
5569        NaN        NaN
5570        NaN        NaN
5571        NaN        NaN

[5572 rows x 5 columns]>

In [49]:
df.shape #size/dimension of dataframe

(5572, 5)

In [51]:
df.isnull().sum()

v1               0
v2               0
Unnamed: 2    5522
Unnamed: 3    5560
Unnamed: 4    5566
dtype: int64

In [52]:
df.isna().sum()

v1               0
v2               0
Unnamed: 2    5522
Unnamed: 3    5560
Unnamed: 4    5566
dtype: int64

FEATURE ENGG

In [53]:
import plotly.express as px
df['Length'] = df['v2'].apply(len)  #creates a new column named 'Length' in your DataFrame
fig = px.histogram(df, x='Length', marginal='rug',
 title='Histogram of Text Length')

#df: Specifies the DataFrame to use for plotting.
#x='Length': Sets the 'Length' column as the data for the x-axis.
#marginal='rug': Adds a 'rug' plot to the margin, which shows the individual data points along the x-axis.
#title='Histogram of Text Length': Sets the title of the histogram.

fig.update_layout(
 xaxis_title='Length',
 yaxis_title='Frequency',
 showlegend=True)
#xaxis_title='Length': Labels the x-axis as 'Length'.
#yaxis_title='Frequency': Labels the y-axis as 'Frequency'.

In [54]:
import plotly.express as px
df['Length'] = df['v2'].apply(len)
fig = px.histogram(df, x='Length', color='v1', marginal='rug',title='Histogram of Text Length by Category')
#x='Length': Uses the 'Length' column for the x-axis.
#color='v1': This crucial parameter tells Plotly to color the bars of the histogram based on the values in the v1 column (e.g., 'ham' vs. 'spam'). This allows for a direct visual comparison of text length distributions between different categories.
#marginal='rug': Adds a rug plot for individual data points.
#title='Histogram of Text Length by Category': Sets a descriptive title.

fig.update_layout(
 xaxis_title='Length',
 yaxis_title='Frequency',
 showlegend=True)
#xaxis_title='Length': Labels the x-axis.
#yaxis_title='Frequency': Labels the y-axis.

In [55]:
df.loc[:,'Category']=df.v1.map({'ham':0,'spam':1})

In [56]:
df['Category']=df['Category'].astype(int)

In [58]:
df.head()

,v1,v2,Unnamed: 2,Unnamed: 3,Unnamed: 4,Length,Category
0,ham,"Go until jurong point, crazy.. Available only ...",NaN,NaN,NaN,111,0
1,ham,Ok lar... Joking wif u oni...,NaN,NaN,NaN,29,0
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,NaN,NaN,NaN,155,1
3,ham,U dun say so early hor... U c already then say...,NaN,NaN,NaN,49,0
4,ham,"Nah I don't think he goes to usf, he lives aro...",NaN,NaN,NaN,61,0

In [57]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
# Split data into features (X) and target (y)
X= df['v2']
y = df['Category']
# TF-IDF Vectorization
tfidf_vectorizer = TfidfVectorizer(max_features=5000) # Limit features for efficiency
X_tfidf = tfidf_vectorizer.fit_transform(X)

In [59]:
# Split dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(
    X_tfidf, y, test_size=0.2, random_state=42
)

print("Training set shape:", X_train.shape)
print("Testing set shape:", X_test.shape)

Training set shape: (4457, 5000)
Testing set shape: (1115, 5000)

In [60]:
# Initialize SVM model (linear kernel for text classification)
svm_model = SVC(kernel="linear", random_state=42)

In [61]:
#train model
svm_model.fit(X_train, y_train)

SVC(kernel='linear', random_state=42)

In [62]:
#predict on test set
y_pred_svm = svm_model.predict(X_test)

In [63]:
# Evaluate performance
accuracy_svm  = accuracy_score(y_test, y_pred_svm)
precision_svm = precision_score(y_test, y_pred_svm)
recall_svm    = recall_score(y_test, y_pred_svm)
f1_svm        = f1_score(y_test, y_pred_svm)

In [64]:
print("\nSVM Model Performance:")
print(f"Accuracy  : {accuracy_svm:.5f}")
print(f"Precision : {precision_svm:.4f}")
print(f"Recall    : {recall_svm:.4f}")
print(f"F1-Score  : {f1_svm:.4f}")

SVM Model Performance:
Accuracy  : 0.98206
Precision : 0.9924
Recall    : 0.8733
F1-Score  : 0.9291